routes/web.php
<?php

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::resource('/admin/beranda', 'Web\Admin\BerandaController');
Route::resource('/admin/dana', 'Web\Admin\DanaController');
Route::resource('/admin/saldo', 'Web\Admin\SaldoController');

app/Dana.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Dana extends Model
{
    protected $dates = ['tanggal'];
    protected $fillable = [
        'id_tahun', 'id_tahap', 'tanggal', 'dana', 'ket'
    ];
}

app/Http/Controllers/Web/Admin/DanaController.php
<?php

namespace App\Http\Controllers\Web\Admin;

use App\Dana;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Meta;
use App\Tahap;
use App\Tahun;

class DanaController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index()
    {
        $no = 1;
        $mtahun = Meta::where('id', 1)->get()->first();
        $tahun = Tahun::where('tahun', $mtahun->meta_value)->get()->first();
        $mtahap = Meta::where('id', 2)->get()->first();
        $tahap = Tahap::where('tahap', $mtahap->meta_value)->where('id_tahun', $tahun->id)->get()->first();

        $dana = Dana::where('id_tahun', $tahun->id)
            ->where('id_tahap', $tahap->id)->get()->all();

        return view('admin.dana.view', compact('no', 'dana'));
    }

    public function create()
    {
        //
    }

    public function store(Request $request)
    {
        $mtahun = Meta::where('id', 1)->get()->first();
        $tahun = Tahun::where('tahun', $mtahun->meta_value)->get()->first();
        $mtahap = Meta::where('id', 2)->get()->first();
        $tahap = Tahap::where('tahap', $mtahap->meta_value)->where('id_tahun', $tahun->id)->get()->first();

        $request->validate([
            'dana' => 'required',
            'ket' => 'required',
        ]);

        $data = $request->all();
        $data['id_tahun'] = $tahun->id;
        $data['id_tahap'] = $tahap->id;

        Dana::create($data);

        $notification = array(
            'message' => 'Dana masuk baru berhasil ditambah.',
            'alert-type' => 'info'
        );

        return redirect()->route('dana.index')->with($notification);
    }

    public function show($id)
    {
        //
    }

    public function edit($id)
    {
        //
    }

    public function update(Request $request, $id)
    {
        //
    }

    public function destroy($id)
    {
        //
    }
}

resources/views/admin/dana/view.blade.php
@extends('layouts.admin')

@section('content')

<section class="content-header">
  <h1>
    Dana Masuk
  </h1>
</section>

<section class="content">
  <div class="row">
    <div class="col-md-12">

      <div class="box box-primary">
        <div class="box-header">
          <h3 class="box-title">Data Dana Masuk</h3>
        </div>
        <div class="box-body">
          <form action="{{ route('dana.store') }}" method="POST" class="form-horizontal">
            @csrf
            @include('form.tambah._admin_dana')
          </form>
        </div>
        <hr>
        <div class="box-body" style="overflow-x:auto;">
          <table id="example1" class="table table-bordered table-striped">
            <thead>
              <tr>
                <th>No</th>
                <th>Tanggal</th>
                <th>Dana</th>
                <th>Keterangan</th>
                <th>Action</th>
              </tr>
            </thead>
            <tbody>
              @foreach($dana as $item)
              <tr>
                <td>{{ $no++ }}</td>
                <td>{{ $item->tanggal->format('d/m/Y') }}</td>
                <td>{{ $item->dana }}</td>
                <td>{{ $item->ket }}</td>
                <td>
                  <form action="{{ route('dana.destroy',$item->id) }}" method="POST">

                    <a class="btn btn-primary" href="{{ route('dana.edit',$item->id) }}">Edit</a>

                    @csrf
                    @method('DELETE')

                    <button type="submit" class="btn btn-danger">Delete</button>
                  </form>
                </td>
              </tr>
              @endforeach
            </tbody>
          </table>
        </div>
        <!-- /.box-body -->
      </div>
    </div>
  </div>
</section>
@endsection